In [ ]:
import pandas as pd

In [ ]:
tn_2021 = pd.read_csv('/content/tn_2021_results.csv')

In [ ]:
tn_2026 = pd.read_csv('/content/tn_2026_results.csv')

In [ ]:
con_master = pd.read_csv('/content/constituency_master.csv')

In [ ]:
tn_2026.head()

,constituency,ac_number,candidate,party,votes,turnout,reserved,region
0,Gummidipoondi,1,S.VIJAYAKUMAR,TVK,94320,NaN,GEN,Chennai Metro
1,Gummidipoondi,1,SUDHAKAR.V,AIADMK,66375,NaN,GEN,Chennai Metro
2,Gummidipoondi,1,T.J.GOVINDARAJAN,DMK,62492,NaN,GEN,Chennai Metro
3,Gummidipoondi,1,"R.SRIDAR. B.L.,",NTK,4756,NaN,GEN,Chennai Metro
4,Gummidipoondi,1,NOTA,NOTA,937,NaN,GEN,Chennai Metro

In [ ]:
tn_2026.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4257 entries, 0 to 4256
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   constituency  4257 non-null   object
 1   ac_number     4257 non-null   int64
 2   candidate     4257 non-null   object
 3   party         4257 non-null   object
 4   votes         4257 non-null   int64
 5   turnout       0 non-null      float64
 6   reserved      4257 non-null   object
 7   region        4257 non-null   object
dtypes: float64(1), int64(2), object(5)
memory usage: 266.2+ KB

In [ ]:
tn_2021.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4232 entries, 0 to 4231
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   constituency  4232 non-null   object
 1   ac_number     4232 non-null   int64
 2   candidate     4232 non-null   object
 3   party         4232 non-null   object
 4   votes         4232 non-null   int64
 5   turnout       4232 non-null   float64
 6   reserved      4232 non-null   object
 7   region        4232 non-null   object
dtypes: float64(1), int64(2), object(5)
memory usage: 264.6+ KB

In [ ]:
tn_2021['winner_vote'] = tn_2021.groupby('constituency')['votes'].max()

In [ ]:
tn_2021['winner_vote'].value_counts()

Series([], Name: count, dtype: int64)

In [ ]:
tn_2021['winner_vote']

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
        ..
4227   NaN
4228   NaN
4229   NaN
4230   NaN
4231   NaN
Name: winner_vote, Length: 4232, dtype: float64

In [ ]:
tn_2021_winners = tn_2021.loc[tn_2021.groupby('constituency')['votes'].idxmax()]
tn_2021_winners = tn_2021_winners[['constituency', 'candidate', 'party', 'votes']]
tn_2021_winners = tn_2021_winners.rename(columns={'candidate': 'winner_candidate_2021', 'party': 'winner_party_2021', 'votes': 'winner_votes_2021'})
display(tn_2021_winners.head())

      constituency winner_candidate_2021 winner_party_2021  winner_votes_2021
610        Alandur         T.M.Anbarasan               DMK             116785
3264      Alangudi    SIVA.V.MEYYANATHAN               DMK              87935
4053     Alangulam    PAUL MANOJ PANDIAN            AIADMK              74153
4079  Ambasamudram              E.SUBAYA            AIADMK              85211
108       Ambattur         JOSEPH SAMUEL               DMK             114554

In [ ]:
tn_2021 = pd.merge(tn_2021, tn_2021_winners, on='constituency', how='left')
display(tn_2021.head())

,constituency,ac_number,candidate,party,votes,turnout,reserved,region,winner_vote,winner_candidate_2021,winner_party_2021,winner_votes_2021
0,Gummidipundi,1,GOVINDARAJAN T.J,DMK,126452,78.08,GEN,Chennai Metro,NaN,GOVINDARAJAN T.J,DMK,126452
1,Gummidipundi,1,PRAKASH M,PMK,75514,78.08,GEN,Chennai Metro,NaN,GOVINDARAJAN T.J,DMK,126452
2,Gummidipundi,1,USHA,NTK,11701,78.08,GEN,Chennai Metro,NaN,GOVINDARAJAN T.J,DMK,126452
3,Gummidipundi,1,DILLIY K.M,DMDK,2576,78.08,GEN,Chennai Metro,NaN,GOVINDARAJAN T.J,DMK,126452
4,Gummidipundi,1,None Of The Above,NOTA,1783,78.08,GEN,Chennai Metro,NaN,GOVINDARAJAN T.J,DMK,126452

In [ ]:
print(tn_2021[['constituency', 'party', 'votes']])

      constituency                                     party   votes
0     Gummidipundi                                       DMK  126452
1     Gummidipundi                                       PMK   75514
2     Gummidipundi                                       NTK   11701
3     Gummidipundi                                      DMDK    2576
4     Gummidipundi                                      NOTA    1783
...            ...                                       ...     ...
4227     Killiyoor                                       IND     235
4228     Killiyoor                                       IND     213
4229     Killiyoor                                       IND     213
4230     Killiyoor  National Democratic Party of South India     186
4231     Killiyoor    Tamilnadu Mahatma Gandhi Makkal Katchi     162

[4232 rows x 3 columns]

In [ ]:
from enum import unique
tn_2021['party'].value_counts(ascending= False)

party
IND                                          2073
NOTA                                          234
NTK                                           234
AIADMK                                        191
DMK                                           188
                                             ...
South India Forward Bloc                        1
Universal Brotherhood Movement                  1
Anaithu Ulaga Tamilargal Munnetra Kalagam       1
Ulaga Makkal Katchi                             1
Tamilnadu Mahatma Gandhi Makkal Katchi          1
Name: count, Length: 109, dtype: int64

In [ ]:
tn_2026['party'].value_counts()

party
IND                           2209
NTK                            234
NOTA                           234
TVK                            233
DMK                            176
                              ...
Republican Party of India        1
Bharatha Makkal Katchi           1
Kamarajar Deseeya Congress       1
Rashtriya Janata Dal             1
Indian Christian Front           1
Name: count, Length: 105, dtype: int64

In [ ]:
tn_2026.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4257 entries, 0 to 4256
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   constituency  4257 non-null   object
 1   ac_number     4257 non-null   int64
 2   candidate     4257 non-null   object
 3   party         4257 non-null   object
 4   votes         4257 non-null   int64
 5   turnout       0 non-null      float64
 6   reserved      4257 non-null   object
 7   region        4257 non-null   object
dtypes: float64(1), int64(2), object(5)
memory usage: 266.2+ KB

In [ ]:
tn_2026_winners = tn_2026.loc[tn_2026.groupby('constituency')['votes'].idxmax()]
tn_2026_winners = tn_2026_winners[['constituency', 'candidate', 'party', 'votes']]
tn_2026_winners = tn_2026_winners.rename(columns={'candidate': 'winner_candidate_2026', 'party': 'winner_party_2026', 'votes': 'winner_votes_2026'})

In [ ]:
tn_2026 = pd.merge(tn_2026, tn_2026_winners, on='constituency', how='left')

In [ ]:
tn_2026

,constituency,ac_number,candidate,party,votes,turnout,reserved,region,winner_candidate_2026,winner_party_2026,winner_votes_2026
0,Gummidipoondi,1,S.VIJAYAKUMAR,TVK,94320,NaN,GEN,Chennai Metro,S.VIJAYAKUMAR,TVK,94320
1,Gummidipoondi,1,SUDHAKAR.V,AIADMK,66375,NaN,GEN,Chennai Metro,S.VIJAYAKUMAR,TVK,94320
2,Gummidipoondi,1,T.J.GOVINDARAJAN,DMK,62492,NaN,GEN,Chennai Metro,S.VIJAYAKUMAR,TVK,94320
3,Gummidipoondi,1,"R.SRIDAR. B.L.,",NTK,4756,NaN,GEN,Chennai Metro,S.VIJAYAKUMAR,TVK,94320
4,Gummidipoondi,1,NOTA,NOTA,937,NaN,GEN,Chennai Metro,S.VIJAYAKUMAR,TVK,94320
...,...,...,...,...,...,...,...,...,...,...,...
4252,Killiyoor,234,BABY RAJ. P,IND,162,NaN,GEN,South,RAJESH KUMAR. S,INC,66434
4253,Killiyoor,234,RUBIN ANTONY,Tamizhaga Vaazhvurimai Katchi,156,NaN,GEN,South,RAJESH KUMAR. S,INC,66434
4254,Killiyoor,234,SATHEESH. S,IND,128,NaN,GEN,South,RAJESH KUMAR. S,INC,66434
4255,Killiyoor,234,JUSTIN. T,Indian Christian Front,85,NaN,GEN,South,RAJESH KUMAR. S,INC,66434
4256,Killiyoor,234,DR. RAMACHANDRAN. M,IND,73,NaN,GEN,South,RAJESH KUMAR. S,INC,66434

In [ ]:
tn_2026['constituency'].nunique()

233

In [ ]:
tn_2026.groupby('constituency')['ac_number'].nunique().sort_values(ascending=False).head()

constituency
Tiruppattur     2
Alangudi        1
Alangulam       1
Ambasamudram    1
Ambattur        1
Name: ac_number, dtype: int64

In [ ]:
tn_2026[tn_2026['constituency'] == 'Tiruppattur'].sort_values('votes', ascending=False)[
    ['constituency', 'candidate', 'party', 'votes']
]

,constituency,candidate,party,votes
986,Tiruppattur,DR.THIRUPATHI. N,TVK,105098
3404,Tiruppattur,SEENIVASA SETHUPATHY. R,TVK,83375
3405,Tiruppattur,PERIAKARUPPAN. KR,DMK,83374
987,Tiruppattur,NALLATHAMBI. A,DMK,56835
988,Tiruppattur,GNANASEKAR. A,AMMK,30003
3406,Tiruppattur,THIRUMARAN. K.C,BJP,29054
3407,Tiruppattur,RAMYA MOHAN,NTK,15291
989,Tiruppattur,ARUMUGAM. V,NTK,5482
3408,Tiruppattur,RAJA. K.P.M,IND,753
3409,Tiruppattur,NOTA,NOTA,747
3410,Tiruppattur,UMADEVI. S,All India Puratchi Thalaivar Makkal Munnettra ...,611
3411,Tiruppattur,VISHWANATHAN. S,IND,496
990,Tiruppattur,RAJESH. S,Tamizhaga Vaazhvurimai Katchi,486
991,Tiruppattur,NOTA,NOTA,464
992,Tiruppattur,THIRUPATHI. N,IND,447
993,Tiruppattur,VENKATESAN. K,IND,408
994,Tiruppattur,SEKAR. N,All India Youth Development Party,387
3412,Tiruppattur,SHANMUGAM. M,IND,383
3413,Tiruppattur,DR.VINAYAGA MEYYARASU. T,IND,380
995,Tiruppattur,RAJIV GANDHI. S,Bahujan Samaj Party,361
996,Tiruppattur,THIRUPATHI. C,IND,355
3414,Tiruppattur,MARIMUTHU. S,IND,350
997,Tiruppattur,VIJAYAKUMAR. G,Aanaithinthiya Jananayaka Pathukappu Kazhagam,345
998,Tiruppattur,THIRUPATHI. S,IND,339
999,Tiruppattur,RAGUJOSEPH. J,IND,308
3415,Tiruppattur,BAKIYALAKSHMI. M,IND,266
3416,Tiruppattur,PIRAMAN. P,IND,223
1000,Tiruppattur,KALASTHIRI. S,All India Uzhavargal Uzhaippalargal Katchi,208
1001,Tiruppattur,GNANASEKARAN. R,IND,206
1002,Tiruppattur,NALLATHAMBI. R,IND,192
1003,Tiruppattur,SANKAR. S,IND,182
3417,Tiruppattur,MALLIKA. A,IND,143
1004,Tiruppattur,DR.POOVALAGI. P,IND,139
1005,Tiruppattur,SATHIYAMOORTHY. S,Makkal Nala Kazhagam,136
3418,Tiruppattur,SETHU. P,IND,135
3419,Tiruppattur,PANCHAVARNAM. M,IND,129
1006,Tiruppattur,BALABHARATHI. S.V,IND,128
1007,Tiruppattur,GNANASEKARAN. M,IND,127
1008,Tiruppattur,MOHAN RAJ. R,IND,119
1009,Tiruppattur,ANJALI. M,IND,115
1010,Tiruppattur,GOVIND. T.G,IND,55

In [ ]:
winners = tn_2026.loc[tn_2026.groupby('constituency')['votes'].idxmax()]

print("Total constituencies:", winners['constituency'].nunique())
print("\nSeats by party:")
print(winners['party'].value_counts())

Total constituencies: 233

Seats by party:
party
TVK       107
DMK        59
AIADMK     47
INC         5
PMK         4
VCK         2
CPI(M)      2
IUML        2
CPI         2
AMMK        1
BJP         1
DMDK        1
Name: count, dtype: int64